---
- hosts: amazonweb
  become_user: root
  become: true
  tasks:
    - name: copy war file onto app server
      copy:
        src: /etc/ansible/playbook/webapp/target/webapp.war
        dest: /opt/apache-tomcat-8.5.50/webapps/
