---
- hosts: amazonweb
  become_user: root
  become: yes
  tasks:

    - name: download java
      yum: name=java-1.8.0 state=present
  
    - name: download tomcat tar file from internet
      get_url: url=http://www-us.apache.org/dist/tomcat/tomcat-8/v8.5.55/bin/apache-tomcat-8.5.55.tar.gz dest=/opt

    - name: unarchieve files
      unarchive:
        src: /opt/apache-tomcat-8.5.55.tar.gz
        dest: /opt
        remote_src: yes

    - name: change port
      lineinfile: dest=/opt/apache-tomcat-8.5.55/conf/server.xml regexp='Connector port="8080"' line="<Connector port="8081""
      
    - name: start tomcat service
      command: nohup /opt/apache-tomcat-8.5.55/bin/startup.sh
